version: "3.8"

services:
  java:
    image: zarbose/javadegree-java
    build:
      context: ./java
      args:
        EXPOSE_METRICS_PORT: '9301'
    container_name: java
    networks:
      - net-java
    #ports:
    #  - "9301:9301"  # Dev only
    depends_on:
      - kafka

  kafka:
    image: zarbose/javadegree-kafka
    build:
      context: ./kafka
      args:
        EXPOSE_METRICS_PORT: '9301'
    container_name: kafka
    networks:
      - net-java
      - net-kafka
    ports:
      - "9094:9094"  # Dev only
    #  - "9301:9301"  # Dev only
    volumes:
      - kafka_data:/bitnami
    environment:
      KAFKA_ENABLE_KRAFT: yes                   # Default
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true # Default
      ALLOW_PLAINTEXT_LISTENER: yes             # Dev only (no SASL_SSL)
      # Do not put hostname (kafka) below when using multi networks, cause Kafka will resolve it with IP of its own interface in FIRST network (by alphabetic order)
      KAFKA_CFG_LISTENERS: INSIDE://:9092,OUTSIDE://:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  grafana:
    image: zarbose/javadegree-grafana
    build:
      context: ./grafana
    container_name: grafana
    networks:
      - net-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: zarbose/javadegree-prometheus
    build:
      context: ./prometheus
    container_name: prometheus
    networks:
      - net-java
      - net-kafka
      - net-grafana
      - net-node
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  # EXPORTERS

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - net-node
    #ports:
    #  - "9301:9301"  # Dev only
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=:9301'
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    networks:
      - net-kafka
    #ports:
    #  - "9301:9301" # Dev only
    command:
      - '--kafka.server=kafka:9092'
      - '--kafka.version=3.4.0'
      - '--web.listen-address=:9301'
    depends_on:
      - kafka
    restart: on-failure

networks:
  net-java:
  net-kafka:
  net-grafana:
  net-node:

volumes:
  kafka_data:
  prometheus_data:
  grafana_data:
