version: "3.8"

services:
  java:
    image: zarbose/javadegree-java
    build:
      context: ./java
    container_name: java
    networks:
      - net_Java_Kafka

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    container_name: kafka
    networks:
      - net_Java_Kafka
      - net_Kafka_Prom
    environment:
      KAFKA_ENABLE_KRAFT: yes                   # Default
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true # Default
      ALLOW_PLAINTEXT_LISTENER: yes             # Dev only (no SASL_SSL)
      KAFKA_CFG_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER


volumes:
  kafka_data:
    driver: local

networks:
  net_Java_Kafka:
  net_Kafka_Prom:
  net_Prom_Graf:
