version: "3.8"

services:
  java:
    image: zarbose/javadegree-java
    build:
      context: ./java
    container_name: java
    networks:
      - net_Java_Kafka

  kafka:
    image: zarbose/javadegree-kafka
    build:
      context: ./kafka
    container_name: kafka
    ports:
      - "9094:9094"
      - "12345:12345" #Dev by Martin
    networks:
      - net_Java_Kafka
      - net_Kafka_Prom
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_ENABLE_KRAFT: yes                   # Default
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true # Default
      ALLOW_PLAINTEXT_LISTENER: yes             # Dev only (no SASL_SSL)
      KAFKA_CFG_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OPTS: -javaagent:/bitnami/kafka/jmx_prometheus_javaagent-0.18.0.jar=12345:/bitnami/kafka/config/config.yaml

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - net_Kafka_Prom
      - net_Prom_Graf
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/

volumes:
  kafka_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  net_Java_Kafka:
  net_Kafka_Prom:
  net_Prom_Graf:
