{
 "title": "JMX Metrics",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "JVM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "jmx-exporter" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_info{job=\"$job\"},instance)"
   },
   {
    "name": "mempool",
    "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$instance\"}, pool)"
   },
   {
    "name": "memarea",
    "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$instance\"}, area)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed virtual memory"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  }
 ]
}