name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/java"
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/javadegree-java:latest

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/grafana"
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/javadegree-grafana:latest

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/kafka"
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/javadegree-kafka:latest

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/prometheus"
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/javadegree-prometheus:latest
